/*****************************************************************************************************
 * 本代码版权归Quber所有，All Rights Reserved (C) 2015-2088
 * 联系人邮箱：qubernet@163.com
 *****************************************************************************************************
 * 创建人：Quber
 * 创建说明：初始化一些数据或变量
 *****************************************************************************************************
 * 修改人：
 * 修改时间：
 * 修改说明：
*****************************************************************************************************/

var initObj = {
    //EasyUI 图标对象
    fontIconObj: [
        {
            name: '列表常用', list: [
                { name: '加号', icon: 'plus', module: '' },
                { name: '加号圆圈', icon: 'plus-circle', module: '添加' },
                { name: '编辑', icon: 'edit', module: '修改' },
                { name: '信息', icon: 'info-circle', module: '查看' },
                { name: '叉号', icon: 'times', module: '' },
                { name: '叉号圆圈', icon: 'times-circle', module: '删除' },
                { name: '查询', icon: 'search', module: '' },
                { name: '查询加号', icon: 'search-plus', module: '查询' },
                { name: '查询减号', icon: 'search-minus', module: '' },
            ]
        },
        {
            name: '编辑常用', list: [
                { name: '保存', icon: 'save', module: '保存' },
                { name: '叉号圆圈', icon: 'times-circle', module: '取消' },
                { name: '查询加号', icon: 'search-plus', module: '点击选择' },
                { name: '叉号', icon: 'times', module: '清除' },
            ]
        },
        {
            name: '统计图标', list: [
                { name: '柱状图', icon: 'bar-chart', module: '' },
                { name: '柱状图简单', icon: 'bar-chart-o', module: '' },
                { name: '线形图', icon: 'line-chart', module: '' },
                { name: '饼状图', icon: 'pie-chart', module: '' },
                { name: '区域图', icon: 'area-chart', module: '' },
            ]
        },
        {
            name: '文件图标', list: [
                { name: '文件', icon: 'file', module: '' },
                { name: '文件简单', icon: 'file-o', module: '' },
                { name: '代码', icon: 'file-code-o', module: '' },
                { name: '图片', icon: 'file-image-o', module: '' },
                { name: '文本文件', icon: 'file-text', module: '' },
                { name: '文本文件简单', icon: 'file-text-o', module: '' },
                { name: 'word', icon: 'file-word-o', module: '' },
                { name: 'excel', icon: 'file-excel-o', module: '' },
                { name: 'ppt', icon: 'file-powerpoint-o', module: '' },
                { name: 'pdf', icon: 'file-pdf-o', module: '' },
                { name: 'zip', icon: 'file-zip-o', module: '' },
                { name: 'sound', icon: 'file-sound-o', module: '' },
                { name: 'video', icon: 'file-video-o', module: '' },
            ]
        },
        {
            name: '表单图标', list: [
                { name: '勾选', icon: 'check', module: '' },
                { name: '勾选圆形', icon: 'check-circle', module: '' },
                { name: '勾选圆形简单', icon: 'check-circle-o', module: '' },
                { name: '勾选方形', icon: 'check-square', module: '' },
                { name: '勾选方形简单', icon: 'check-square-o', module: '' },
                { name: '加号方形', icon: 'plus-square', module: '' },
                { name: '加号方形简单', icon: 'plus-square-o', module: '' },
                { name: '减号方形', icon: 'minus-square', module: '' },
                { name: '减号方形简单', icon: 'minus-square-o', module: '' },
                { name: '圆形', icon: 'circle', module: '' },
                { name: '圆形简单', icon: 'circle-o', module: '' },
                { name: '圆形点', icon: 'dot-circle-o', module: '' },
                { name: '用户', icon: 'user', module: '' },
                { name: '用户加号', icon: 'user-plus', module: '' },
                { name: '用户叉号', icon: 'user-times', module: '' },
                { name: '用户复数', icon: 'users', module: '' },
                { name: '用户秘密', icon: 'user-secret', module: '' },
                { name: '用户医生', icon: 'user-md', module: '' },
                { name: '疑问', icon: 'question', module: '' },
                { name: '疑问圆形', icon: 'question-circle', module: '' },
                { name: '疑问圆形简单', icon: 'question-circle-o', module: '' },
                { name: '星号', icon: 'asterisk', module: '' },
                { name: '@', icon: 'at', module: '' },
                { name: '条形码', icon: 'barcode', module: '' },
                { name: 'bar', icon: 'bars', module: '' },
                { name: '漏洞', icon: 'bug', module: '' },
                { name: '日历', icon: 'calendar', module: '' },
                { name: '日历简单', icon: 'calendar-o', module: '' },
                { name: '日历选中简单', icon: 'calendar-check-o', module: '' },
                { name: '日历减号简单', icon: 'calendar-minus-o', module: '' },
                { name: '日历加号简单', icon: 'calendar-plus-o', module: '' },
                { name: '日历叉号简单', icon: 'calendar-times-o', module: '' },
                { name: '时间', icon: 'clock-o', module: '' },
                { name: '克隆', icon: 'clone', module: '' },
                { name: '复制', icon: 'copy', module: '' },
                { name: '云', icon: 'cloud', module: '' },
                { name: '云下载', icon: 'cloud-download', module: '' },
                { name: '云上传', icon: 'cloud-upload', module: '' },
                { name: '代码', icon: 'code', module: '' },
                { name: '代码交叉', icon: 'code-fork', module: '' },
                { name: '设置', icon: 'cog', module: '' },
                { name: '设置复数', icon: 'cogs', module: '' },
                { name: '评论', icon: 'comment', module: '' },
                { name: '评论简单', icon: 'comment-o', module: '' },
                { name: '评论点', icon: 'commenting', module: '' },
                { name: '评论点简单', icon: 'commenting-o', module: '' },
                { name: '评论复数', icon: 'comments', module: '' },
                { name: '评论复数简单', icon: 'comments-o', module: '' },
                { name: '指南针', icon: 'compass', module: '' },
                { name: '版权', icon: 'copyright', module: '' },
                { name: '剪切', icon: 'crop', module: '' },
                { name: '数据库', icon: 'database', module: '' },
                { name: '桌面', icon: 'desktop', module: '' },
                { name: '下载', icon: 'download', module: '' },
                { name: '擦除', icon: 'eraser', module: '' },
                { name: '交换', icon: 'exchange', module: '' },
                { name: '警告', icon: 'exclamation-triangle', module: '' },
            ]
        },
        {
            name: '生活图标', list: [
                { name: '银行', icon: 'bank', module: '' },
                { name: '汽车', icon: 'car', module: '' },
                { name: '公共汽车', icon: 'bus', module: '' },
                { name: '床', icon: 'bed', module: '' },
                { name: '盲人', icon: 'blind', module: '' },
                { name: '轮椅', icon: 'wheelchair-alt', module: '' },
                { name: '救护车', icon: 'ambulance', module: '' },
                { name: '自行车', icon: 'bicycle', module: '' },
                { name: '战斗机', icon: 'fighter-jet', module: '' },
                { name: '摩托车', icon: 'motorcycle', module: '' },
                { name: '船', icon: 'ship', module: '' },
                { name: '火箭', icon: 'rocket', module: '' },
                { name: '飞机', icon: 'plane', module: '' },
                { name: '航天飞机', icon: 'space-shuttle', module: '' },
                { name: '货车', icon: 'truck', module: '' },
                { name: '火车', icon: 'train', module: '' },
                { name: '出租车', icon: 'taxi', module: '' },
                { name: '地铁', icon: 'subway', module: '' },
                { name: '音量控制手机', icon: 'volume-control-phone', module: '' },
                { name: '电话', icon: 'phone', module: '' },
                { name: '电话方形', icon: 'phone-square', module: '' },
                { name: '手机', icon: 'mobile', module: '' },
                { name: '麦克风', icon: 'microphone', module: '' },
                { name: '麦克风禁止', icon: 'microphone-slash', module: '' },
                { name: '耳机', icon: 'headphones', module: '' },
                { name: '禁止', icon: 'ban', module: '' },
                { name: '天平', icon: 'balance-scale', module: '' },
                { name: '电池没电', icon: 'battery-0', module: '' },
                { name: '电池1', icon: 'battery-1', module: '' },
                { name: '电池2', icon: 'battery-2', module: '' },
                { name: '电池3', icon: 'battery-3', module: '' },
                { name: '电池满电', icon: 'battery-4', module: '' },
                { name: '啤酒', icon: 'beer', module: '' },
                { name: '铃铛', icon: 'bell', module: '' },
                { name: '铃铛简单', icon: 'bell-o', module: '' },
                { name: '铃铛禁止', icon: 'bell-slash', module: '' },
                { name: '铃铛禁止简单', icon: 'bell-slash-o', module: '' },
                { name: '望远镜', icon: 'binoculars', module: '' },
                { name: '生日蛋糕', icon: 'birthday-cake', module: '' },
                { name: '炸弹', icon: 'bomb', module: '' },
                { name: '书', icon: 'book', module: '' },
                { name: '书签', icon: 'bookmark', module: '' },
                { name: '书签简单', icon: 'bookmark-o', module: '' },
                { name: '公文包', icon: 'briefcase', module: '' },
                { name: '建筑', icon: 'building', module: '' },
                { name: '建筑简单', icon: 'building-o', module: '' },
                { name: '闪电', icon: 'bolt', module: '' },
                { name: '喇叭', icon: 'bullhorn', module: '' },
                { name: '计算器', icon: 'calculator', module: '' },
                { name: '照相机', icon: 'camera', module: '' },
                { name: '照相机', icon: 'camera-retro', module: '' },
                { name: '购物车', icon: 'shopping-cart', module: '' },
                { name: '购物车打开', icon: 'opencart', module: '' },
                { name: '购物车向下', icon: 'cart-arrow-down', module: '' },
                { name: '购物车加号', icon: 'cart-plus', module: '' },
                { name: '咖啡', icon: 'coffee', module: '' },
                { name: '信用卡', icon: 'credit-card', module: '' },
                { name: '信用卡', icon: 'credit-card-alt', module: '' },
                { name: '餐具', icon: 'cutlery', module: '' },
                { name: '钻石', icon: 'diamond', module: '' },
                { name: '信封', icon: 'envelope', module: '' },
                { name: '信封简单', icon: 'envelope-o', module: '' },
                { name: '信封方形', icon: 'envelope-square', module: '' },
            ]
        },
        {
            name: '应用图标', list: [
                { name: '苹果', icon: 'apple', module: '' },
                { name: '苹果浏览器', icon: 'safari', module: '' },
                { name: '安卓', icon: 'android', module: '' },
                { name: '蓝牙', icon: 'bluetooth', module: '' },
                { name: '蓝牙简单', icon: 'bluetooth-b', module: '' },
                { name: '谷歌', icon: 'google', module: '' },
                { name: '谷歌', icon: 'google-plus', module: '' },
                { name: '谷歌浏览器', icon: 'chrome', module: '' },
                { name: 'css', icon: 'css3', module: '' },
                { name: 'html5', icon: 'html5', module: '' },
                { name: 'ie浏览器', icon: 'internet-explorer', module: '' },
                { name: 'edge浏览器', icon: 'edge', module: '' },
                { name: '火狐浏览器', icon: 'firefox', module: '' },
                { name: 'facebook', icon: 'facebook', module: '' },
                { name: 'facebook方形', icon: 'facebook-square', module: '' },
                { name: '字体', icon: 'font-awesome', module: '' },
                { name: 'github', icon: 'github', module: '' },
                { name: 'in', icon: 'linkedin', module: '' },
                { name: 'in方形', icon: 'linkedin-square', module: '' },
                { name: 'opera浏览器', icon: 'opera', module: '' },
                { name: 'qq', icon: 'qq', module: '' },
                { name: '微信', icon: 'weixin', module: '' },
                { name: '人人', icon: 'renren', module: '' },
                { name: 'skype', icon: 'skype', module: '' },
                { name: 'stack', icon: 'stack-overflow', module: '' },
                { name: 'twitter', icon: 'twitter', module: '' },
                { name: 'usb', icon: 'usb', module: '' },
                { name: '微博', icon: 'weibo', module: '' },
                { name: 'windows', icon: 'windows', module: '' },
                { name: '救护车', icon: 'ambulance', module: '' },
            ]
        }
    ],
    //EasyUI 图标对象
    euiIconObj: {
        //图标域路径
        domain: '/Content/Components/EasyUI/themes/bootstrap/icons/',
        //图标按钮数据列表
        list: [
            { name: 'acenter', suf: '.png' },
            { name: 'add', suf: '.png' },
            { name: 'addfile', suf: '.png' },
            { name: 'addfooter', suf: '.png' },
            { name: 'addheader', suf: '.png' },
            { name: 'additem', suf: '.png' },
            { name: 'addnewds', suf: '.png' },
            { name: 'ahb', suf: '.png' },
            { name: 'ahb1', suf: '.png' },
            { name: 'ahc', suf: '.png' },
            { name: 'ahc1', suf: '.png' },
            { name: 'aht', suf: '.png' },
            { name: 'aht1', suf: '.png' },
            { name: 'aj', suf: '.png' },
            { name: 'al', suf: '.png' },
            { name: 'ann', suf: '.png' },
            { name: 'apply', suf: '.png' },
            { name: 'ar', suf: '.png' },
            { name: 'area', suf: '.png' },
            { name: 'article', suf: '.png' },
            { name: 'attach', suf: '.png' },
            { name: 'attachm', suf: '.png' },
            { name: 'avc', suf: '.png' },
            { name: 'avc1', suf: '.png' },
            { name: 'avl', suf: '.png' },
            { name: 'avl1', suf: '.png' },
            { name: 'avr', suf: '.png' },
            { name: 'avr1', suf: '.png' },

            { name: 'backword', suf: '.png' },
            { name: 'bar', suf: '.png' },
            { name: 'barcode', suf: '.png' },
            { name: 'behindtext', suf: '.png' },
            { name: 'bf', suf: '.png' },
            { name: 'bold', suf: '.png' },
            { name: 'breaking', suf: '.png' },
            { name: 'btf', suf: '.png' },
            { name: 'btft', suf: '.png' },
            { name: 'bub', suf: '.png' },
            { name: 'bug', suf: '.png' },
            { name: 'build', suf: '.png' },

            { name: 'cah', suf: '.png' },
            { name: 'cancel', suf: '.png' },
            { name: 'canlendar', suf: '.png' },
            { name: 'cards', suf: '.png' },
            { name: 'cdsf', suf: '.png' },
            { name: 'cfs', suf: '.png' },
            { name: 'chart', suf: '.png' },
            { name: 'charts', suf: '.png' },
            { name: 'chartssl', suf: '.png' },
            { name: 'chartx', suf: '.png' },
            { name: 'checkbox', suf: '.png' },
            { name: 'clear', suf: '.png' },
            { name: 'clearf', suf: '.png' },
            { name: 'clearfor', suf: '.png' },
            { name: 'clip', suf: '.png' },
            { name: 'close', suf: '.png' },
            { name: 'colors', suf: '.png' },
            { name: 'column', suf: '.png' },
            { name: 'comment', suf: '.png' },
            { name: 'contact', suf: '.png' },
            { name: 'content', suf: '.png' },
            { name: 'contentaa', suf: '.png' },
            { name: 'contentac', suf: '.png' },
            { name: 'contentar', suf: '.png' },
            { name: 'convert', suf: '.png' },
            { name: 'convertp', suf: '.png' },
            { name: 'copy', suf: '.png' },
            { name: 'country', suf: '.png' },
            { name: 'csharp', suf: '.png' },
            { name: 'currency', suf: '.png' },
            { name: 'customg', suf: '.png' },
            { name: 'customz', suf: '.png' },
            { name: 'cut', suf: '.png' },

            { name: 'dayview', suf: '.png' },
            { name: 'db', suf: '.png' },
            { name: 'dbedit', suf: '.png' },
            { name: 'ddoac', suf: '.png' },
            { name: 'ddosc', suf: '.png' },
            { name: 'ddosp', suf: '.png' },
            { name: 'deitc', suf: '.png' },
            { name: 'del', suf: '.png' },
            { name: 'deleteds', suf: '.png' },
            { name: 'deletelist', suf: '.png' },
            { name: 'deletelist1', suf: '.png' },
            { name: 'delgh', suf: '.png' },
            { name: 'design', suf: '.png' },
            { name: 'docmap', suf: '.png' },
            { name: 'download', suf: '.png' },

            { name: 'edit', suf: '.png' },
            { name: 'editf', suf: '.png' },
            { name: 'editwp', suf: '.png' },
            { name: 'emailt', suf: '.png' },
            { name: 'example', suf: '.png' },
            { name: 'export', suf: '.png' },
            { name: 'exportc', suf: '.png' },
            { name: 'exportdoc', suf: '.png' },
            { name: 'exportdocx', suf: '.png' },
            { name: 'exportepub', suf: '.png' },
            { name: 'exportf', suf: '.png' },
            { name: 'exporthtml', suf: '.png' },
            { name: 'exportimg', suf: '.png' },
            { name: 'exportpdf', suf: '.png' },
            { name: 'exporttxt', suf: '.png' },
            { name: 'exportxls', suf: '.png' },
            { name: 'exportxlsx', suf: '.png' },
            { name: 'exportxml', suf: '.png' },
            { name: 'exportxps', suf: '.png' },

            { name: 'feeds', suf: '.png' },
            { name: 'fillb', suf: '.png' },
            { name: 'filter', suf: '.png' },
            { name: 'filterac', suf: '.png' },
            { name: 'filterap', suf: '.png' },
            { name: 'filtersc', suf: '.png' },
            { name: 'filtersp', suf: '.png' },
            { name: 'find', suf: '.png' },
            { name: 'findc', suf: '.png' },
            { name: 'findid', suf: '.png' },
            { name: 'first', suf: '.png' },
            { name: 'folderp', suf: '.png' },
            { name: 'fontsize', suf: '.png' },
            { name: 'fontsized', suf: '.png' },
            { name: 'fontsizei', suf: '.png' },
            { name: 'forcet', suf: '.png' },
            { name: 'forword', suf: '.png' },
            { name: 'fullsa', suf: '.png' },
            { name: 'fullsb', suf: '.png' },
            { name: 'fullsl', suf: '.png' },

            { name: 'gaugesfc', suf: '.png' },
            { name: 'gaugeshc', suf: '.png' },
            { name: 'gaugeslh', suf: '.png' },
            { name: 'gaugeslqc', suf: '.png' },
            { name: 'gaugeslv', suf: '.png' },
            { name: 'gaugesrqc', suf: '.png' },
            { name: 'gaugestfc', suf: '.png' },
            { name: 'grid', suf: '.png' },
            { name: 'groupfc', suf: '.png' },

            { name: 'help', suf: '.png' },
            { name: 'hiddentext', suf: '.png' },
            { name: 'hide', suf: '.png' },
            { name: 'highlieht', suf: '.png' },
            { name: 'highlightfc', suf: '.png' },
            { name: 'history', suf: '.png' },
            { name: 'home', suf: '.png' },

            { name: 'ide', suf: '.png' },
            { name: 'image', suf: '.png' },
            { name: 'importimg', suf: '.png' },
            { name: 'indd', suf: '.png' },
            { name: 'indi', suf: '.png' },
            { name: 'info', suf: '.png' },
            { name: 'inline', suf: '.png' },
            { name: 'insert', suf: '.png' },
            { name: 'insertrf', suf: '.png' },
            { name: 'italic', suf: '.png' },

            { name: 'key', suf: '.png' },
            { name: 'kpi', suf: '.png' },

            { name: 'language', suf: '.png' },
            { name: 'last', suf: '.png' },
            { name: 'listb', suf: '.png' },
            { name: 'listm', suf: '.png' },
            { name: 'listn', suf: '.png' },
            { name: 'loadform', suf: '.png' },
            { name: 'loadpages', suf: '.png' },
            { name: 'lock', suf: '.png' },

            { name: 'mail', suf: '.png' },
            { name: 'masterf', suf: '.png' },
            { name: 'merge', suf: '.png' },
            { name: 'monthview', suf: '.png' },
            { name: 'morelo', suf: '.png' },
            { name: 'movedown', suf: '.png' },
            { name: 'moveup', suf: '.png' },

            { name: 'navibar', suf: '.png' },
            { name: 'new', suf: '.png' },
            { name: 'newcontact', suf: '.png' },
            { name: 'newfeed', suf: '.png' },
            { name: 'newmail', suf: '.png' },
            { name: 'next', suf: '.png' },
            { name: 'next1', suf: '.png' },
            { name: 'none', suf: '.png' },
            { name: 'notes', suf: '.png' },

            { name: 'open', suf: '.png' },
            { name: 'openhlccs', suf: '.png' },
            { name: 'opers', suf: '.png' },

            { name: 'palette', suf: '.png' },
            { name: 'paste', suf: '.png' },
            { name: 'picsfc', suf: '.png' },
            { name: 'picsoc', suf: '.png' },
            { name: 'pie', suf: '.png' },
            { name: 'pielt', suf: '.png' },
            { name: 'piesd', suf: '.png' },
            { name: 'piovt', suf: '.png' },
            { name: 'prev', suf: '.png' },
            { name: 'preview', suf: '.png' },
            { name: 'previous', suf: '.png' },
            { name: 'print', suf: '.png' },
            { name: 'printd', suf: '.png' },
            { name: 'printpdf', suf: '.png' },
            { name: 'pro', suf: '.png' },
            { name: 'prod', suf: '.png' },
            { name: 'prof', suf: '.png' },
            { name: 'prolanguage', suf: '.png' },
            { name: 'pub', suf: '.png' },

            { name: 'ranarea', suf: '.png' },
            { name: 'reading', suf: '.png' },
            { name: 'redo', suf: '.png' },
            { name: 'refresh', suf: '.png' },
            { name: 'refresh1', suf: '.png' },
            { name: 'remove', suf: '.png' },
            { name: 'removei', suf: '.png' },
            { name: 'replace', suf: '.png' },
            { name: 'return', suf: '.png' },
            { name: 'return1', suf: '.png' },
            { name: 'role', suf: '.png' },

            { name: 'save', suf: '.png' },
            { name: 'saveas', suf: '.png' },
            { name: 'saveclose', suf: '.png' },
            { name: 'savedia', suf: '.png' },
            { name: 'savenew', suf: '.png' },
            { name: 'savepages', suf: '.png' },
            { name: 'saveto', suf: '.png' },
            { name: 'scripts', suf: '.png' },
            { name: 'search', suf: '.png' },
            { name: 'selectall', suf: '.png' },
            { name: 'selectall1', suf: '.png' },
            { name: 'send', suf: '.png' },
            { name: 'sendbt', suf: '.png' },
            { name: 'sendbw', suf: '.png' },
            { name: 'sendcsv', suf: '.png' },
            { name: 'sendimg', suf: '.png' },
            { name: 'sendmht', suf: '.png' },
            { name: 'sendpdf', suf: '.png' },
            { name: 'sendrtf', suf: '.png' },
            { name: 'sendtoback', suf: '.png' },
            { name: 'sendtxt', suf: '.png' },
            { name: 'sendxls', suf: '.png' },
            { name: 'sendxlsx', suf: '.png' },
            { name: 'showhidden', suf: '.png' },
            { name: 'showtr', suf: '.png' },
            { name: 'showwto', suf: '.png' },
            { name: 'sidesrb', suf: '.png' },
            { name: 'snap', suf: '.png' },
            { name: 'sol', suf: '.png' },
            { name: 'sortasc', suf: '.png' },
            { name: 'sortdesc', suf: '.png' },
            { name: 'spellcyt', suf: '.png' },
            { name: 'splita', suf: '.png' },
            { name: 'sqare', suf: '.png' },
            { name: 'squeeze', suf: '.png' },
            { name: 'status', suf: '.png' },
            { name: 'steparea', suf: '.png' },
            { name: 'stretch', suf: '.png' },
            { name: 'strikeout', suf: '.png' },
            { name: 'show', suf: '.png' },
            { name: 'strikeoutout', suf: '.png' },
            { name: 'subscript', suf: '.png' },
            { name: 'sug', suf: '.png' },
            { name: 'summary', suf: '.png' },
            { name: 'supscript', suf: '.png' },
            { name: 'switch', suf: '.png' },

            { name: 'tag', suf: '.png' },
            { name: 'task', suf: '.png' },
            { name: 'team', suf: '.png' },
            { name: 'technology', suf: '.png' },
            { name: 'textbox', suf: '.png' },
            { name: 'time', suf: '.png' },
            { name: 'timelineview', suf: '.png' },
            { name: 'today', suf: '.png' },

            { name: 'underline', suf: '.png' },
            { name: 'underlined', suf: '.png' },
            { name: 'underlinew', suf: '.png' },
            { name: 'up', suf: '.png' },

            { name: 'user', suf: '.png' },
            { name: 'user1', suf: '.png' },
            { name: 'usergroup', suf: '.png' },
            { name: 'userset', suf: '.png' },

            { name: 'vb', suf: '.png' },
            { name: 'ver', suf: '.png' },
            { name: 'video', suf: '.png' },
            { name: 'viewweb', suf: '.png' },

            { name: 'watermarker', suf: '.png' },
            { name: 'weekend', suf: '.png' },
            { name: 'weekview', suf: '.png' },
            { name: 'win', suf: '.png' },
            { name: 'withtext', suf: '.png' },
            { name: 'wizard', suf: '.png' },
            { name: 'workweekview', suf: '.png' },
            { name: 'zoom100', suf: '.png' },
            { name: 'zoomin', suf: '.png' },
            { name: 'zoomout', suf: '.png' }
        ]
    }
};


